version: "3.8"
services:
  server:
    container_name: example-host
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - minecraft.env
    ports:
      - "25565:25565"
  database:
    container_name: example-mysql
    image: mysql:5.7
    env_file:
      - mysql.env
    ports:
      - "3306:3306"