package at.warix.data.entities;

import java.time.LocalDateTime;
import java.util.UUID;

public class Vote {
    private long voteId;
    private UUID playerUuid;
    private String playerName;
    private LocalDateTime votedOn;

    /**
     * Standard constructor
     *
     * @param voteId     Voting ID - auto-generated by MySQL
     * @param playerUuid Minecraft UUID of the player
     * @param playerName The Minecraft player name
     * @param votedOn    The date and time on which the vote has been done
     */
    public Vote(long voteId, UUID playerUuid, String playerName, LocalDateTime votedOn) {
        this.voteId = voteId;
        this.playerUuid = playerUuid;
        this.playerName = playerName;
        this.votedOn = votedOn;
    }

    /**
     * A constructor for creating temp votes which haven't been added to the database
     * @param playerUuid The Minecraft UUID of the player
     * @param playerName The Minecraft player name
     */
    public Vote(UUID playerUuid, String playerName) {
        this.playerUuid = playerUuid;
        this.playerName = playerName;
    }

    public long getVoteId() {
        return voteId;
    }

    public void setVoteId(long voteId) {
        this.voteId = voteId;
    }

    public UUID getPlayerUuid() {
        return playerUuid;
    }

    public void setPlayerUuid(UUID playerUuid) {
        this.playerUuid = playerUuid;
    }

    public String getPlayerName() {
        return playerName;
    }

    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    public LocalDateTime getVotedOn() {
        return votedOn;
    }

    public void setVotedOn(LocalDateTime votedOn) {
        this.votedOn = votedOn;
    }
}
